### ISSUE TITLE
Add "Dodging Burnout, 4 Hours at a Time" to Resources

### ISSUE THREAD

**Issue by bemosior** [reignite/burnout.io#15]
https://medium.com/@jpaulreed/dodging-burnout-4-hours-at-a-time-965f1921e6a2

**Comment by bemosior** [comment]
@preed How do you feel about this as the article hook?
>"It took a few days to properly unwind, disconnect from email, Twitter, and my phone, but it was worth it... probably most importantly, it left me with a serious sense of long-term perspective and a well of energy to tap into to start working on these new projects."

**Comment by preed** [comment]
Hey Ben,

Let me noodle on it a bit; that's an OK hook, but it makes it sound like you need to take a few days off to get the benefits, and the article is actually about the opposite (finding small chunks of time to sustainably avoid burnout.)

Gimme a couple days and I'll get back to you? :-)

**Comment by bemosior** [comment]
You're right that it doesn't communicate the meaning very well.  I couldn't
seem to piece something together that worked. Thanks for taking a look!

**Comment by bemosior** [comment]
I'm going to run with the below for now (just let me know if you would like something different). Per #22, it seems we might be changing how we list resources soon so that a quote isn't necessary.

>While critically important as a tool to help, these solutions also don’t directly address the path to burnout. They don’t tackle the systemic problems within both startups and larger organizations that lead to burnout. They gloss over the patterned behaviors of sociopathic (or even merely incompetent) managers.

**Comment by preed** [comment]
Hey Ben,

Good call; this kinda fell through the cracks for me. If I come up with any changes/additions for this entry, I'll look at #22 and submit a PR.
