### ISSUE TITLE
Add "A Year of Fire and Fog" to Resources

### ISSUE THREAD

**Issue by bemosior** [reignite/burnout.io#16]
https://medium.com/@nobert/a-year-of-fire-and-fog-2c68f90c74e4

**Comment by bemosior** [comment]
@nobert Do you have any thoughts on a quote/hook to use? So far I am partial to one of these:

> There I was; an ops team of one* heading into our most important quarter with a mountain of work to do and the added pressure of having committed to an influential board member that we’d have a smooth quarter. We agreed that we’d celebrate our success on the other side of it. I had put my reputation on the line.

\

> It is true that I would insist that I could handle it, and I guess I did, but don’t organizations have a responsibility to their employees to stop them from harming themselves in the name of the job?

 \

> So I did what any highly privileged person should do in this situation: I handed in my resignation with no plan other than to sleep for a month, play video games for another month, then maybe start to figure things out. What happened next is what should have happened from the start...

**Comment by balupton** [comment]
If you don't get a reply, I'd go with the last quote.

**Comment by nobert** [comment]
@bemosior I am partial to the second quote but am not really tied to it. I gladly defer to you on this :)

**Comment by timparenti** [comment]
I think the second one is the most broadly accessible, but I do like the end of the third one, too.

**Comment by bemosior** [comment]
In favor of accessibility and author preference, the second quote seems like a good choice. :) Thanks everyone!
