### ISSUE TITLE
Teamup with Open-Sourcing Mental Illness

### ISSUE THREAD

**Issue by balupton** [reignite/burnout.io#22]
http://funkatron.com/osmi.html / http://funkatron.com/about.html

/cc @funkatron - would be cool if burnout.io and osmi could unify their fantastic work and evangelism somehow - I like how burnout.io is a community open-source thing, whereas osmi seems to be an individual controlled thing - thoughts? Specifically, the burnout.io resources and pull requests section could quickly lend to duplicated content. Perhaps an open-source data file approach like https://github.com/jaspervdj/static-site-generator-comparison could work? Which then both sites then utilise.

**Comment by balupton** [comment]
Seems there is also http://prompt.engineyard.com/resources.html on this front too.

**Comment by funkatron** [comment]
What can I do?

**Comment by bemosior** [comment]
Burnout.io is also more or less individual-controlled (I'm a single point of failure at best). Opening that up to more people certainly would be a move in the right direction, and I'm certainly open to collaborative efforts. I don't have as much time as I'd like, but I'll gladly help as able!

**Comment by balupton** [comment]
So as a proposal, prompt, osmi, and burnout.io are all maintaining their own resources listings. It would be great to unify this, so instead of a user having to check and find 3 different sources of information, there is one that is maintained by all 3 groups - which is shared to the different locations.

I was able to accomplish this unification with https://staticsitegenerators.net which is powered by this YAML data file: https://github.com/jaspervdj/static-site-generator-comparison - people can then submit pull requests to that YAML file that has additional meta attributes, which one of the many maintainers then reviews the pull request and merges it in (as well as automated tests to verify the links are still valid), then when a change occurs a hook then tells the website to regenerate with the latest details, the website then pulls in additional live data (like github stars, etc) and makes the enhanced data accessible via a sortable HTML listing, as well as a enhanced JSON listing if others want to incorporate the data in their own systems. It's successfully helped eliminated the redundancy of new "10 static-site generators" blog posts that you see each week.

I'd imagine a similar thing happening here, at least for the resources. The resources could be done up as a YAML file with the following attributes:

- excerpt (e.g. a quote from the link)
- title
- url
- author
- author_url
- tags (e.g. video, podcast, article, conference, company, blog)
- date_added
- date_published

Then each of our sites could then utilise the data.

I don't anticipate this eliminating or replacing anyone's existing efforts, but would serve as a great landing page to direct to other individuals efforts while reducing redundancy.

I have the bandwidth to implement such a thing if it is established to be worthwhile.

**Comment by bemosior** [comment]
I definitely like the idea of externalizing a resource list and offering it as public information. I may be straying a little from the original thought, but it would be interesting to explore the option of building something embeddable in order to keep the user within the originating site and minimize the abruptness of the user experience. I suspect that would also improve adoption.

Regardless, it probably makes sense for it to have its own repo (and treat it as a dependency within burnout.io). We could potentially utilize the Reignite organizational namespace for such a repository, if it would make sense.

**Comment by funkatron** [comment]
I think having a central repo of data is a great idea. I do think that most people will use the centralized version to get information, and I think it probably is better to have a single "brand" (for lack of a better term) as the face.

**Comment by balupton** [comment]
@funkatron cool, sounds like we are all in agreement there.

/cc'ing @GregBaugues for transparency and inclusiveness, Greg what are your thoughts on [this proposal](https://github.com/reignite/burnout.io/issues/22#issuecomment-91098864) a few comments up?

**Comment by AaronSachs** [comment]
Hi @balupton , @bemosior just referred me to here with regard to retooling resources, and breaking it out into it's own thing. I'd love to help in any way that I can, or start getting the ball rolling on making this happen. Let me know what I can do!

**Comment by balupton** [comment]
Hey! I'm currently without computer access, delegating to the others!

**Comment by GregBaugues** [comment]
Hey y'all sorry for the delay. 

This is a great idea. Would love to have a central resource list to point folks. Thanks so much for doing this.

**Comment by bemosior** [comment]
What do we need to determine in order to design and build an effective technical solution?

I think we could start here: 

* What is the demographic we are trying to reach?
* What makes a collection of resources helpful to that demographic?

I think it would also be interesting to answer those questions for the different individual sites in order to better understand what a collective answer might be. For burnout.io, I believe the demographic is individuals experiencing work-related fatigue and/or burnout. The resources seem to be helpful if they are relatable, such as blog posts about others' work experiences. The burnout.io resources page has too many items to be useful in a list form, and I agree with the assessment in #28 that using quotes isn't helpful to our demographic.

**Comment by AaronSachs** [comment]
Agreed. I think that we should at least split it out by something to the
effect of books, web resources (e.g., blogs, articles from the medical
community, etc., and even burnout's own chat room (gitter, IRC, whatever)),
etc. I'm not sure of Ben Mosior's long-term vision for what the site could
be, but it'd be great if we could somehow provide some sort of support net
in the form of peer-to-peer accountability. I can flesh this out a bit more
later this evening as far as what I mean by the peer-to-peer accountability
stuff.

**Comment by bemosior** [comment]
If I could "wave a magic wand" and have a solution for web resources, the visitors of burnout.io would arrive at the resources page and immediately be able to find something relevant. In my mind, that means the individual resources are filterable by and have been categorized according to subtopics (e.g., "management", "open-source", "anxiety"). I would like to be able to suggest subtopics at the top that more closely fit burnout.io's niche, while also enabling access to all possible subtopics. Each site that implements the resources list could do the same.

Maybe some sort of selector like this, perhaps?
![Mockup of subtopics](http://i.imgur.com/5r7VLpl.png)

**Comment by AaronSachs** [comment]
Ohhhh! That would totally work, I think! But what does that do for using
Pico for the site? Are we going to have to switch to another framework?

**Comment by bemosior** [comment]
@AaronSachs I hadn't considered different media and so on. That's an interesting point.

This will turn into its own project, I hope.

**Comment by bemosior** [comment]
@AaronSachs, I'm not sure if this meets what you're thinking of with peer-to-peer accountability, but I was chatting in [hangops (on Slack)](http://signup.hangops.com/) and @supine pointed me towards http://devpressed.com.

**Comment by GregBaugues** [comment]
I started depressed a couple years ago. Mostly handsoff on it. Been really
impressed by what the community has done with it. Happy to chat more about
it.

**Comment by AaronSachs** [comment]
Heya @bemosior -- I wanted to dredge this topic back up. With the RTD build, I'm sure we can split off the resources fairly easily. Maybe split the current quotes away from the actual resources? Or, with RTD, we can set the TOC to go so deep--in this case, maybe retool the resources page and then have the resources show up in a drop-down in the sidebar?

**Comment by bemosior** [comment]
I've lost quite a bit of steam here but definitely like the ideas. If we can achieve a more friendly format for the resources, I'm all for it (even if it's not what we were dreaming up before). Usefulness > all. In that realm, I don't think preserving the quotes are even necessary.

**Comment by AaronSachs** [comment]
Cool. I'll go ahead and start retooling the resources then and aim to make it more along the lines of what @funkatron @balupton @GregBaugues seemed to be getting at earlier in the thread.

**Comment by asachs01** [comment]
Hi all, I'm going to go ahead and close this out. It's been ~3 years on this issue being open. If there's anything we want to do in terms of updating the project, please open up a new issue.
