### ISSUE TITLE
Rename "Actionables" and migrate content

### ISSUE THREAD

**Issue by bemosior** [reignite/burnout.io#24]
The origins of this project is burnout in IT, and there is sadly a significant possibility that management plays an antagonistic role for a significant portion of those visiting the site. The term "actionable" has origins in law and management, so that's not a great foundation for the name of a primary section of the site. 

Additionally, @iennae made some additions to the Actionables in #14 that stand on their own quite effectively. They're lost, however, at the bottom of the rest of the items in that section. 

Given these two situations, I'm now in favor of condensing the "Actionables" content prior to #14, migrating it to the front page (more content, fewer clicks), additionally migrating the content in #14 to its own section (perhaps titled "More Ideas"?), and removing the "Actionables" section altogether.

The new layout could look something like this:
```
Burnout.io
├── Resources
├── More Ideas
└── Contribute
```
I think this will also give us an opportunity to revise and unify the content prior to #14, as it is a little disjoint. The inherent difficulty with collaborative writing is that, while the the content is extremely valuable, it's a bit difficult to read with the different writing styles and organization.

It would be great to hear some opinions before deciding whether to embark on this change. :smile:

**Comment by bemosior** [comment]
Thanks to @AaronSachs for splitting the content out! :+1:

**Comment by AaronSachs** [comment]
Hi @bemosior , I'm going to close this one off, since it looks like we've tackled this one.

**Comment by bemosior** [comment]
I never got around to renaming actionables, but maybe it's not necessary? :+1:
