### ISSUE TITLE
Replace ableist words

### ISSUE THREAD

**Issue by nslater** [reignite/burnout.io#25]
"Sanity" is the flipside to "insanity", and thus ableist. I suggest you replace all instances of it with something more descriptive. "Mental health" seems like it might work.

Old phrasing:

>  If the choice is between your sanity and your work, one of those is going to win (and it needs to be your sanity)!

New phrasing:

>  If the choice is between your mental health and your work, one of those is going to win (and it needs to be your mental health)!

**Comment by bemosior** [comment]
No objections here. I'm still learning about what kind of phrasing concerns to be aware of. Do you have any resources you could recommend that can help bring clarity to this issue?

It's going to be a little while before I can set aside some quiet time to edit content. If you have some time, could you help adjust the content via PR? If not that's fine. I'll get to it at my next opportunity.

**Comment by bemosior** [comment]
Sorry, "phrasing concerns" sounds like I'm trivializing. Not my intent.

**Comment by bemosior** [comment]
I found [this MVC article](https://modelviewculture.com/pieces/the-hearing-monoculture-rejects-those-who-cant-hear) to be helpful in improving my understanding.  Lots of insightful reference material in there as well.

**Comment by nslater** [comment]
Thanks, I'll prepare a PR.

In the meantime, these links are good:

http://disabledfeminists.com/2010/05/17/guest-post-from-rmj-ableist-word-profile-crazy/
http://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html
http://isthisableism.tumblr.com/sluralternatives

**Comment by nslater** [comment]
There's also this sentence:

> Yes, it's crazy, but sometimes all it takes is explaining the problem and talking it out with management and coworkers.

I'd like to remove "crazy", but I'm not sure of what to replace it with here. Suggestions? Could we drop the first part of the sentence entirely?

**Comment by bemosior** [comment]
Dropping it altogether is probably the best. I think the original intent was to acknowledge the hopelessness that may preclude the action, but the meaning's clear without it.

I wrote most of these lines and feel pretty terrible about it. Thanks so much for taking the time to help correct this (both the words and the person behind them).

**Comment by nslater** [comment]
Thanks a lot!
