### ISSUE TITLE
Retool Resources

### ISSUE THREAD

**Issue by AaronSachs** [reignite/burnout.io#28]
Hi Ben, 

I've been looking over the resources page, and it seems we could beef it up--maybe make it more of a collection of resources, since right now, the _feel_ of the page is that it's more a collection of quotes regarding burnout. I'm not sure if this is the intent, or if you're open to changing it, but I'd love to help in any way I can.

Aaron

**Comment by bemosior** [comment]
My original thought was that the quotes could help guide a visitor to relevant resources, but I see how the implementation almost emphasizes the quote over the resource.

There was another interesting idea (#22) to break the resources out into their own self-contained entity, but we haven't made much progress yet.

We're certainly in a state of flux, at this point. Any thoughts on direction are welcome!

**Comment by AaronSachs** [comment]
Ah! Cool, then I guess this one's set--may as well put the effort into #22 :)
