### ISSUE TITLE
Another resource

### ISSUE THREAD

**Issue by iennae** [reignite/burnout.io#40]
http://www.mind.org.uk/

**Comment by iennae** [comment]
https://docs.google.com/document/d/1PGLZPz8XKbASMYFAVjTAJ3W9oXu2FUZvUsGcV8yc84E/edit also has a long list of helpful resources.

**Comment by AaronSachs** [comment]
Nice! I can try and get those incorporated (might have to do a new page)
Thursday/Friday.

**Comment by AaronSachs** [comment]
Hi @iennae . I'm adding this in a commit right now. You should see it up by the end of the day :)
