### ISSUE TITLE
Checking in

### ISSUE THREAD

**Issue by asachs01** [reignite/burnout.io#45]
Hi Folks, 

I hope everyone has been doing well. I just wanted to check in--it's been a few months and it's been pretty quiet.

**Comment by bemosior** [comment]
Hi

**Comment by alex7217** [comment]
sup

**Comment by bemosior** [comment]
Haha sorry, just been really busy. Anything I can be immediately helpful with?

**Comment by iennae** [comment]
It's looking great. One of these days we should put together something for the different categories of problems that arise and strategies for handling them.

**Comment by asachs01** [comment]
@bemosior nothing immediately--just checking in. Making sure folks are staying healthy :)

@iennae I think we can start doing that. I'll go ahead and open an issue  so we can start tackling that.
