### ISSUE TITLE
CALL FOR PROPOSALS: DOMAIN

### ISSUE THREAD

**Issue by bemosior** [reignite/burnout.io#73]
The domain is renewing in May of this year at a cost of around $45. I do not plan to renew the domain next year.

According to our analytics, we get maybe 100 views a month, many of which seem to be inauthentic traffic.

Unless I receive alternate proposals, I intend to do the following before the domain renews in 2023:

- Modify the github configuration to end the use of burnout.io and begin using a default github.io domain
- Cease the renewal of the burnout.io domain

**Comment by SilentGlasses** [comment]
If we bring this to a default GitHub domain, would you consider converting this to a Material with MkDocs site?  It's easier to maintain and manage and I'd be happy to help as a maintainer.

**Comment by bemosior** [comment]
No objections from me!

**Comment by bemosior** [comment]
The domain renewal is coming up in May. I have disabled auto-renewal and intend to follow through with the plan described last year when it expires.

**Comment by bemosior** [comment]
The plan has been followed, and the site is now available at [burnoutio.readthedocs.io](https://burnoutio.readthedocs.io).

I completely forgot it was hosted at readthedocs. Any future work to convert it to a MkDocs site will want to take that into account. (Although I suspect that would just be a matter of pointing people at a new GitHub Pages url instead of the readthedocs url.)
