### ISSUE TITLE
Start a community forum

### ISSUE THREAD

**Issue by julianlam** [reignite/burnout.io#9]
Would be a great idea for burnt out devs to be able to talk to one another. Could also work as a resource and build original searchable content for search engines. 

I run a neat forum software called [NodeBB](https://nodebb.org). Can possibly give you guys a good deal to start off with if you don't want to host it yourselves.

**Comment by bemosior** [comment]
Burnout.io has found its niche as an informational resource. I'd love to get a community forum started at some point, but those efforts would likely need to be part of a larger effort. Thanks to @julianlam and @binarycleric for trying to get this started!
